import { jsonSchema2Prisma } from "@graviola/json-schema-prisma-utils";
import { defs } from "@graviola/json-schema-utils";
import { schema } from "@graviola/edb-import-demo-schema";
import type { JSONSchema7 } from "json-schema";
import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const appRoot = join(__dirname, "..");
const prismaDir = join(appRoot, "prisma");
const schemaPath = join(prismaDir, "schema.prisma");
const prismaConfigPath = join(appRoot, "prisma.config.ts");

const DEFAULT_DATABASE_URL =
  "postgresql://graviola:graviola@localhost:5433/import_api";

function requireNixPrismaEngines(): void {
  if (!process.env.PRISMA_QUERY_ENGINE_LIBRARY) {
    console.error(
      "PRISMA_QUERY_ENGINE_LIBRARY is unset. Run inside the Nix dev shell:\n" +
        "  nix develop --command sh -c 'bun run api:db:setup'",
    );
    process.exit(1);
  }
}

function startPostgres(): void {
  console.log("Starting Postgres (docker compose up -d --wait)…");
  execSync("docker compose up -d --wait", {
    cwd: appRoot,
    stdio: "inherit",
  });
}

function injectScalarStringArrays(modelsBlock: string): string {
  let result = modelsBlock;
  for (const [typeName, def] of Object.entries(defs(schema))) {
    const properties = (def as JSONSchema7).properties ?? {};
    const scalarArrays = Object.entries(properties).filter(([, prop]) => {
      const ps = prop as JSONSchema7;
      return (
        ps.type === "array" && (ps.items as JSONSchema7)?.type === "string"
      );
    });
    if (scalarArrays.length === 0) continue;

    const modelRe = new RegExp(
      `(model ${typeName} \\{[\\s\\S]*?)(\\n  idAuthority_authority)`,
    );
    const extraFields = scalarArrays
      .filter(
        ([name]) =>
          !result.includes(`model ${typeName}`) ||
          !new RegExp(`\\n  ${name} `).test(
            result.slice(result.indexOf(`model ${typeName}`)),
          ),
      )
      .map(([name]) => `  ${name} String[]`)
      .join("\n");
    if (!extraFields) continue;

    result = result.replace(modelRe, `$1\n${extraFields}$2`);
  }
  return result;
}

function generatePrismaSchema(): string {
  const modelsBlock = jsonSchema2Prisma(schema, new WeakSet(), {
    databaseProvider: "postgresql",
    reverseMap: {},
  });

  // json-schema-prisma-utils omits idAuthority.id as idAuthority_id when the
  // model already has a primary key field named `id`; prisma-db-impl expects it.
  let modelsPatched = injectScalarStringArrays(modelsBlock);
  modelsPatched = modelsPatched.replace(
    /(\n  idAuthority_authority String\?\n)(  id String @id)/g,
    "$1  idAuthority_id String?\n  type String?\n$2",
  );
  modelsPatched = modelsPatched.replace(
    /(\n  idAuthority_id String\?\n)(  id String @id)/g,
    "$1  type String?\n$2",
  );

  return `generator client {
  provider = "prisma-client-js"
  output   = "../generated/client"
}

datasource db {
  provider = "postgresql"
}

${modelsPatched}`;
}

function writePrismaConfig(): void {
  const content = `// Auto-generated by db:setup — Prisma 7 CLI reads DATABASE_URL here
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
`;
  writeFileSync(prismaConfigPath, content, "utf-8");
  console.log(`Wrote ${prismaConfigPath}`);
}

function listModels(prismaSchema: string): string[] {
  return [...prismaSchema.matchAll(/^model (\w+) \{/gm)].map((m) => m[1]);
}

function writeSchema(content: string): void {
  mkdirSync(prismaDir, { recursive: true });
  writeFileSync(schemaPath, content, "utf-8");
  console.log(`Wrote ${schemaPath}`);
}

function pushAndGenerate(databaseUrl: string): void {
  const env = { ...process.env, DATABASE_URL: databaseUrl };
  console.log("Pushing schema (force reset)…");
  execSync("prisma db push --force-reset --accept-data-loss", {
    cwd: appRoot,
    stdio: "inherit",
    env,
  });
  console.log("Generating Prisma client…");
  execSync("prisma generate", {
    cwd: appRoot,
    stdio: "inherit",
    env,
  });
}

function main(): void {
  requireNixPrismaEngines();
  startPostgres();

  const databaseUrl = process.env.DATABASE_URL ?? DEFAULT_DATABASE_URL;
  process.env.DATABASE_URL = databaseUrl;

  const prismaSchema = generatePrismaSchema();
  writeSchema(prismaSchema);
  writePrismaConfig();

  const models = listModels(prismaSchema);
  pushAndGenerate(databaseUrl);

  console.log("\n── db:setup complete ──");
  console.log(`DATABASE_URL=${databaseUrl}`);
  console.log(`Models (${models.length}): ${models.join(", ")}`);
  console.log(`Prisma client: ${join(appRoot, "generated/client")}`);
}

main();
