/**
 * Prisma ORM adapter.
 *
 * Activated by environment variables:
 *   SQLITE_URL    — e.g. "file:./test.db"  (default, no Docker required)
 *   POSTGRES_URL  — e.g. "postgresql://test:test@localhost:5432/graviola_test"
 *   MARIADB_URL   — e.g. "mysql://test:test@localhost:3306/graviola_test"
 *   MONGODB_URL   — e.g. "mongodb://localhost:27017/graviola_test"
 *
 * Prerequisites (run via `bun run pretest`):
 *   1. scripts/setup-prisma.ts generates prisma/schema.prisma for the target DB
 *   2. `prisma generate` creates the @prisma/client bindings
 *   3. `prisma db push --force-reset` applies the schema to the DB
 *
 * The Prisma client is loaded via dynamic import so this adapter degrades
 * gracefully when `prisma generate` has not been run.
 *
 * Note: Not all operations are supported by Prisma:
 *   - countDocuments: not directly available (workaround possible, marked false for now)
 *   - findDocumentsByLabel: not implemented in prisma-db-impl
 *   - getClasses: not applicable to relational stores
 *   - importDocuments: supported via loadDocument loop
 *   - iterables: not implemented
 */
import type { AbstractDatastore } from "@graviola/edb-global-types";
import { initPrismaStore } from "@graviola/prisma-db-impl";
import { extendSchemaShortcut } from "@graviola/json-schema-utils";
import type { JSONSchema7 } from "json-schema";

import {
  rawTestSchema,
  typeNameToTypeIRI,
  typeIRItoTypeName,
  BASE_IRI,
  primaryFields,
} from "../schema/testSchema";
import type { DatastoreAdapter } from "../types";

/**
 * Attempt to load the Prisma client (generated by `prisma generate`).
 * Returns null if not available.
 */
async function tryLoadPrismaClient(): Promise<any | null> {
  try {
    const { PrismaClient } = await import("@prisma/client");
    return new PrismaClient();
  } catch {
    return null;
  }
}

/**
 * Clear all records in dependency order (children before parents) to
 * avoid FK constraint violations.
 */
async function clearPrismaData(prisma: any): Promise<void> {
  // Item references Category and has M2M with Tag — delete first
  try {
    await prisma.item.deleteMany();
  } catch {
    /* model may not exist for this schema */
  }
  try {
    await prisma.tag.deleteMany();
  } catch {
    /* model may not exist */
  }
  try {
    await prisma.category.deleteMany();
  } catch {
    /* model may not exist */
  }
}

export function createPrismaAdapter(
  name: string,
  databaseUrl: string,
): DatastoreAdapter {
  let prismaClient: any = null;

  // Extend schema to add `id` and `type` fields, matching the generated Prisma schema
  const extendedSchema = extendSchemaShortcut(
    rawTestSchema as unknown as JSONSchema7,
    "type",
    "id",
  );

  return {
    name,

    capabilities: {
      crud: true,
      listDocuments: true,
      findDocuments: true,
      countDocuments: false,
      findDocumentsByLabel: false,
      findDocumentsByAuthorityIRI: false,
      findDocumentsAsFlatResultSet: true,
      getClasses: false,
      importDocuments: true,
      iterables: false,
      filterTyped: true,
      findEntityByTypeName: false,
    },

    setup: async (): Promise<AbstractDatastore> => {
      // Ensure DATABASE_URL is set for the Prisma client to connect
      process.env.DATABASE_URL = databaseUrl;

      prismaClient = await tryLoadPrismaClient();
      if (!prismaClient) {
        throw new Error(
          `${name}: @prisma/client not available. ` +
            "Run `bun run pretest` to generate the Prisma client first.",
        );
      }

      await prismaClient.$connect();

      return initPrismaStore(prismaClient, extendedSchema, primaryFields, {
        jsonldContext: { "@vocab": BASE_IRI },
        defaultPrefix: BASE_IRI,
        typeNameToTypeIRI,
        typeIRItoTypeName,
      });
    },

    clearAll: async (_store: AbstractDatastore) => {
      await clearPrismaData(prismaClient);
    },

    teardown: async () => {
      if (prismaClient) {
        await prismaClient.$disconnect();
        prismaClient = null;
      }
    },
  };
}
