/**
 * W3C PROV-aligned generation activity for computed values, lens migrations, etc.
 * @see https://www.w3.org/TR/prov-o/#Activity
 */
export type GenerationActivity = {
  /** IRI or local id of the generating formula slot. */
  formulaId?: string;
  /** Lens document id when value was migrated at read time. */
  lensId?: string;
  /** Stratification layer when generated by the calc runtime. */
  stratum?: number;
  /** Fingerprint of inputs at generation time. */
  inputFingerprint?: string;
  /** prov:wasAssociatedWith — agent IRI or label. */
  agent?: string;
  /** ISO timestamp (prov:generatedAtTime). */
  generatedAt?: string;
};

export const PROV = {
  wasGeneratedBy: "http://www.w3.org/ns/prov#wasGeneratedBy",
  wasAttributedTo: "http://www.w3.org/ns/prov#wasAttributedTo",
  generatedAtTime: "http://www.w3.org/ns/prov#generatedAtTime",
  Activity: "http://www.w3.org/ns/prov#Activity",
} as const;

export const DCT = {
  created: "http://purl.org/dc/terms/created",
  modified: "http://purl.org/dc/terms/modified",
} as const;

export const GRA = {
  schemaVersion: "https://graviola.gra.one/ns/schemaVersion",
  schemaFingerprint: "https://graviola.gra.one/ns/schemaFingerprint",
  metaSchemaVersion: "https://graviola.gra.one/ns/metaSchemaVersion",
} as const;

/** Map a {@link GenerationActivity} to RDF predicate → literal/object pairs. */
export function generationActivityToPredicates(
  activity: GenerationActivity,
): Record<string, string | number> {
  const out: Record<string, string | number> = {};
  if (activity.formulaId) out["gra:formulaId"] = activity.formulaId;
  if (activity.lensId) out["gra:lensId"] = activity.lensId;
  if (activity.stratum !== undefined) out["gra:stratum"] = activity.stratum;
  if (activity.inputFingerprint)
    out["gra:inputFingerprint"] = activity.inputFingerprint;
  if (activity.agent) out[PROV.wasAttributedTo] = activity.agent;
  if (activity.generatedAt) out[PROV.generatedAtTime] = activity.generatedAt;
  return out;
}
