// Auto-generated by db:setup — Prisma 7 CLI reads DATABASE_URL here
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
