#!/usr/bin/env bun
/**
 * Pre-test setup script for Prisma.
 *
 * 1. Generates prisma/schema.prisma from the test JSON schema
 * 2. Runs `prisma generate` to create @prisma/client bindings
 * 3. Runs `prisma db push --force-reset` to apply schema to the DB
 *
 * Run automatically via `bun run pretest`, or manually:
 *   bun scripts/setup-prisma.ts
 *
 * Environment variables:
 *   SQLITE_URL   — SQLite connection string (default: file:./prisma/test.db)
 *   POSTGRES_URL — PostgreSQL URL (generates a postgresql-flavoured schema)
 *   MARIADB_URL  — MariaDB URL (generates a mysql-flavoured schema)
 *   MONGODB_URL  — MongoDB URL (generates a mongodb-flavoured schema)
 *
 * If SKIP_PRISMA=1 is set, this script exits immediately.
 */
import { writeFileSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import { join } from "path";
import { jsonSchema2Prisma } from "@graviola/json-schema-prisma-utils";
import { extendSchemaShortcut } from "@graviola/json-schema-utils";
import { rawTestSchema } from "../src/schema/testSchema";
import type { JSONSchema7 } from "json-schema";

if (process.env.SKIP_PRISMA === "1") {
  console.log("[setup-prisma] SKIP_PRISMA=1 — skipping Prisma setup.");
  process.exit(0);
}

// ─── Determine database provider ─────────────────────────────────────────────

type PrismaProvider = "sqlite" | "postgresql" | "mysql" | "mongodb";

function detectProvider(): PrismaProvider {
  if (process.env.POSTGRES_URL) return "postgresql";
  if (process.env.MARIADB_URL) return "mysql";
  if (process.env.MONGODB_URL) return "mongodb";
  return "sqlite";
}

function getDatabaseUrl(provider: PrismaProvider): string {
  switch (provider) {
    case "postgresql":
      return process.env.POSTGRES_URL!;
    case "mysql":
      return process.env.MARIADB_URL!;
    case "mongodb":
      return process.env.MONGODB_URL!;
    default:
      return process.env.SQLITE_URL ?? "file:./prisma/test.db";
  }
}

// ─── Generate Prisma schema ───────────────────────────────────────────────────

const provider = detectProvider();
const databaseUrl = getDatabaseUrl(provider);

console.log(`[setup-prisma] Generating schema for provider: ${provider}`);
console.log(`[setup-prisma] Database URL: ${databaseUrl}`);

// Extend schema with `id` and `type` fields (required by initPrismaStore)
const extendedSchema = extendSchemaShortcut(
  rawTestSchema as unknown as JSONSchema7,
  "type",
  "id",
);

const modelDefinitions = jsonSchema2Prisma(extendedSchema, new WeakSet());

// For SQLite, embed the URL directly; for others, use an env var
const urlValue =
  provider === "sqlite" ? `"${databaseUrl}"` : `env("DATABASE_URL")`;

const schemaContent = `// Auto-generated by scripts/setup-prisma.ts — do not edit by hand.
// Re-generate with: bun scripts/setup-prisma.ts

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = ${urlValue}
}

${modelDefinitions}
`;

const prismaDir = join(import.meta.dir, "..", "prisma");
mkdirSync(prismaDir, { recursive: true });

const schemaPath = join(prismaDir, "schema.prisma");
writeFileSync(schemaPath, schemaContent, "utf-8");
console.log(`[setup-prisma] Written: ${schemaPath}`);

// ─── Set DATABASE_URL for prisma CLI ─────────────────────────────────────────

if (provider !== "sqlite") {
  process.env.DATABASE_URL = databaseUrl;
}

// ─── Run prisma generate ─────────────────────────────────────────────────────

console.log("[setup-prisma] Running prisma generate...");
try {
  execSync(`bunx prisma generate --schema=${schemaPath}`, {
    stdio: "inherit",
    env: process.env,
  });
  console.log("[setup-prisma] prisma generate: done");
} catch (e) {
  console.error("[setup-prisma] prisma generate failed:", e);
  process.exit(1);
}

// ─── Run prisma db push ───────────────────────────────────────────────────────

console.log("[setup-prisma] Running prisma db push --force-reset...");
try {
  execSync(
    `bunx prisma db push --force-reset --accept-data-loss --schema=${schemaPath}`,
    {
      stdio: "inherit",
      env: process.env,
    },
  );
  console.log("[setup-prisma] prisma db push: done");
} catch (e) {
  console.error("[setup-prisma] prisma db push failed:", e);
  process.exit(1);
}

console.log("[setup-prisma] Prisma setup complete.");
