/**
 * Shared Prisma setup: write schema + prisma.config, generate client, db push.
 * Used by `setup-prisma.ts` (optional `bun run setup:prisma`) and each Prisma adapter `setup()` before
 * connecting — the generated client must match the datasource provider (sqlite vs mysql, …).
 */
import { writeFileSync, mkdirSync } from "fs";
import { execSync } from "child_process";
import { createRequire } from "node:module";
import { join } from "path";
import { jsonSchema2Prisma } from "@graviola/json-schema-prisma-utils";
import { extendSchemaShortcut } from "@graviola/json-schema-utils";
import { rawTestSchema } from "../src/schema/testSchema";
import type { JSONSchema7 } from "json-schema";

export type PrismaProvider = "sqlite" | "postgresql" | "mysql" | "mongodb";

/** Derive Prisma `datasource provider` from a connection URL (not from env). */
export function databaseUrlToProvider(url: string): PrismaProvider {
  const u = url.trim();
  if (u.startsWith("file:") || u.startsWith("sqlite:")) return "sqlite";
  if (u.startsWith("postgresql:") || u.startsWith("postgres:"))
    return "postgresql";
  if (u.startsWith("mysql:") || u.startsWith("mariadb:")) return "mysql";
  if (u.startsWith("mongodb:")) return "mongodb";
  throw new Error(
    `Unknown Prisma DATABASE_URL scheme (expected file:, postgres:, mysql:, …): ${u.slice(0, 64)}`,
  );
}

const require = createRequire(import.meta.url);

/** Drop cached @prisma/client so the next import() loads the newly generated client. */
export function invalidateGeneratedPrismaClientCache(): void {
  for (const k of Object.keys(require.cache)) {
    if (k.includes("@prisma/client") || k.includes(".prisma/client")) {
      delete require.cache[k];
    }
  }
}

/**
 * Regenerate prisma/schema.prisma for `databaseUrl`, run `prisma generate` + `db push`.
 * Synchronous; throws on failure.
 */
export function runPrismaSetupForUrl(databaseUrl: string): void {
  const provider = databaseUrlToProvider(databaseUrl);

  console.log(`[setup-prisma] Generating schema for provider: ${provider}`);
  console.log(`[setup-prisma] Database URL: ${databaseUrl}`);

  const extendedSchema = extendSchemaShortcut(
    rawTestSchema as unknown as JSONSchema7,
    "type",
    "id",
  );

  const modelDefinitions = jsonSchema2Prisma(extendedSchema, new WeakSet(), {
    databaseProvider: provider,
    reverseMap: {},
  });

  const schemaContent = `// Auto-generated by setupPrismaCore — do not edit by hand.
// Regenerated when the setup:prisma script runs or a Prisma adapter connects.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
}

${modelDefinitions}
`;

  const appRoot = join(import.meta.dir, "..");
  const prismaDir = join(appRoot, "prisma");
  mkdirSync(prismaDir, { recursive: true });

  const schemaPath = join(prismaDir, "schema.prisma");
  writeFileSync(schemaPath, schemaContent, "utf-8");
  console.log(`[setup-prisma] Written: ${schemaPath}`);

  const prismaConfigPath = join(appRoot, "prisma.config.ts");
  const prismaConfigContent = `// Used by Prisma 7+ CLI; connection URL is not allowed in schema.prisma
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
`;
  writeFileSync(prismaConfigPath, prismaConfigContent, "utf-8");
  console.log(`[setup-prisma] Written: ${prismaConfigPath}`);

  const env = { ...process.env, DATABASE_URL: databaseUrl };

  console.log("[setup-prisma] Running prisma generate...");
  execSync("bunx prisma generate", {
    stdio: "inherit",
    env,
    cwd: appRoot,
  });
  invalidateGeneratedPrismaClientCache();

  console.log("[setup-prisma] Running prisma db push --force-reset...");
  execSync("bunx prisma db push --force-reset --accept-data-loss", {
    stdio: "inherit",
    env,
    cwd: appRoot,
  });

  console.log("[setup-prisma] Prisma setup complete.");
}
