import type {
  PrimaryFieldDeclaration,
  SPARQLCRUDOptions,
  SPARQLFlavour,
  StringToIRIFn,
  IRIToStringFn,
  WalkerOptions,
} from "@graviola/edb-core-types";
import type { MetaStampingConfig } from "@graviola/meta-schema";
import type { BaseStore, SchemaRegistry } from "@graviola/store-core";
import type { JSONSchema7 } from "json-schema";

export type DatasourceProvider =
  | "sqlite"
  | "postgresql"
  | "mysql"
  | "mariadb"
  | "mongodb"
  | string;

export type OxigraphBackendSpec = {
  kind: "oxigraph";
  /** Turtle string loaded into the in-process store before first use. */
  initialData?: string;
  /** Base IRI for Turtle parse (defaults to `defaultPrefix`). */
  baseIri?: string;
};

export type SparqlBackendSpec = {
  kind: "sparql";
  endpoint: string;
  flavour?: SPARQLFlavour;
  /** CONSTRUCT Accept format. Default inferred from flavour (`ntriples` for oxigraph). */
  constructResultFormat?: "turtle" | "ntriples";
  /**
   * Named graph for this store instance. Writes use WITH / GRAPH via
   * `defaultUpdateGraph`; reads append `?default-graph-uri=` (Oxigraph and
   * SPARQL 1.1 dataset params — required because Oxigraph unscoped queries
   * do not see named-graph triples; verified E-0 2026-08-09).
   */
  graph?: string;
};

export type PrismaBackendSpec = {
  kind: "prisma";
  datasourceUrl: string;
  provider?: DatasourceProvider;
  /**
   * Optional pre-built Prisma client. When omitted, the factory tries
   * `new PrismaClient({ datasources: { db: { url } } })` from `@prisma/client`
   * (works for Prisma 6 SQLite; Prisma 7 adapters must pass `prisma` explicitly).
   */
  prisma?: Record<string, unknown>;
  /**
   * Generated by `jsonSchema2PrismaWithManifest` — multi-value list representations.
   * Typed loosely here to avoid a hard dep on json-schema-prisma-utils.
   */
  persistenceManifest?: {
    databaseProvider: string;
    types: Record<string, Record<string, unknown>>;
  };
};

export type StoreBackendSpec =
  | OxigraphBackendSpec
  | SparqlBackendSpec
  | PrismaBackendSpec;

export type CreateStoreFromSpecOptions<
  R extends SchemaRegistry = SchemaRegistry,
> = {
  schema: JSONSchema7;
  /** Defaults to first `@vocab` / schema `$id` / `"http://example.org/"`. */
  defaultPrefix?: string;
  typeNameToTypeIRI?: StringToIRIFn;
  typeIRItoTypeName?: IRIToStringFn;
  primaryFields?: Partial<PrimaryFieldDeclaration>;
  jsonldContext?: object | string;
  defaultLimit?: number;
  backend: StoreBackendSpec;
  /** Optional SPARQL queryBuildOptions overrides (flavour, primaryFields, …). */
  queryBuildOptions?: Record<string, unknown>;
  /** Graph extraction options for loadOne / CONSTRUCT hydration. */
  walkerOptions?: Partial<WalkerOptions>;
  /** Defaults for loadOne CONSTRUCT (maxRecursion, includeRelationsByDefault, …). */
  sparqlLoadOptions?: Pick<
    SPARQLCRUDOptions,
    "maxRecursion" | "includeRelationsByDefault"
  >;
  /** System-asserted entity `$meta` stamping on upsert (SPARQL / Oxigraph backends). */
  metaStamping?: MetaStampingConfig;
  /**
   * Fact-level statement metadata (`$stmt`) configuration. Enables the
   * `statements` capability (`writeStatements` / `loadStatements`) — required
   * for calc materialization. `policies` keys are `"<TypeName>.<dot.path>"`.
   * `encoding` applies to SPARQL backends only (`statement-node` default;
   * `rdf-12` needs Oxigraph ≥ 0.5). Prisma uses the side-table encoding and
   * rejects MongoDB. Typed loosely to avoid a hard dep on
   * `@graviola/statement-meta`.
   */
  statementMeta?: {
    policies: Record<string, "always" | "never">;
    encoding?: "statement-node" | "rdf-12";
    /**
     * StatementSchema profile (base profile extended by a fact-level meta
     * model). Extension fields only persist when the profile declares them;
     * omitted → framework base profile. SPARQL / Oxigraph backends.
     */
    statementSchema?: JSONSchema7;
    retention?: "all" | "latest" | { keepLast: number };
    retentionByPath?: Record<string, "all" | "latest" | { keepLast: number }>;
  };
  /**
   * Calc materialization config. When present (together with `statementMeta`
   * — calc materialization needs `writeStatements`/`loadStatements`), the
   * built store gets the typed `Calc` facet, with one profile binding per root
   * type, and advertises it through `capabilities.calc` and `profiles.calc`.
   * `profile` and `host` stay `unknown` at this public Layer 1/2 boundary so
   * the exported factory options do not expose calc-engine/formula-dependency
   * types or create a runtime dependency; attachment validates them through
   * type-only casts before calling the lazily imported engine.
   */
  calc?: {
    bindings: Array<{
      rootTypeName: string;
      profile: unknown;
      domainSchema: JSONSchema7;
      agent?: string;
    }>;
    /**
     * Calc host capabilities for slot placement filtering (`CalcHostCapabilities`
     * from `@graviola/calc-engine`). Typed as `unknown` here to avoid a hard Layer
     * 2 dependency in `store-factory`. When omitted, defaults to
     * `SERVER_CALC_HOST` in Bun/Node and `BROWSER_FORM_HOST` in the browser.
     */
    host?: unknown;
  };
};

export type CreatedStore<R extends SchemaRegistry = SchemaRegistry> =
  BaseStore<R> & Record<string, unknown>;

export type CreateStoreResult<R extends SchemaRegistry = SchemaRegistry> = {
  store: CreatedStore<R>;
  /** Logical type names from `schema.definitions`. */
  typeNames: string[];
  /** Tear down backend resources (Prisma `$disconnect`, etc.). */
  dispose?: () => Promise<void>;
};
