import type {
  PrimaryFieldDeclaration,
  SPARQLFlavour,
  StringToIRIFn,
  IRIToStringFn,
} from "@graviola/edb-core-types";
import type { BaseStore, SchemaRegistry } from "@graviola/store-core";
import type { JSONSchema7 } from "json-schema";

export type DatasourceProvider =
  | "sqlite"
  | "postgresql"
  | "mysql"
  | "mariadb"
  | "mongodb"
  | string;

export type OxigraphBackendSpec = {
  kind: "oxigraph";
  /** Turtle string loaded into the in-process store before first use. */
  initialData?: string;
  /** Base IRI for Turtle parse (defaults to `defaultPrefix`). */
  baseIri?: string;
};

export type SparqlBackendSpec = {
  kind: "sparql";
  endpoint: string;
  flavour?: SPARQLFlavour;
  /** CONSTRUCT Accept format. Default inferred from flavour (`ntriples` for oxigraph). */
  constructResultFormat?: "turtle" | "ntriples";
};

export type PrismaBackendSpec = {
  kind: "prisma";
  datasourceUrl: string;
  provider?: DatasourceProvider;
  /**
   * Optional pre-built Prisma client. When omitted, the factory tries
   * `new PrismaClient({ datasources: { db: { url } } })` from `@prisma/client`
   * (works for Prisma 6 SQLite; Prisma 7 adapters must pass `prisma` explicitly).
   */
  prisma?: Record<string, unknown>;
  /**
   * Generated by `jsonSchema2PrismaWithManifest` — multi-value list representations.
   * Typed loosely here to avoid a hard dep on json-schema-prisma-utils.
   */
  persistenceManifest?: {
    databaseProvider: string;
    types: Record<string, Record<string, unknown>>;
  };
};

export type StoreBackendSpec =
  | OxigraphBackendSpec
  | SparqlBackendSpec
  | PrismaBackendSpec;

export type CreateStoreFromSpecOptions<
  R extends SchemaRegistry = SchemaRegistry,
> = {
  schema: JSONSchema7;
  /** Defaults to first `@vocab` / schema `$id` / `"http://example.org/"`. */
  defaultPrefix?: string;
  typeNameToTypeIRI?: StringToIRIFn;
  typeIRItoTypeName?: IRIToStringFn;
  primaryFields?: Partial<PrimaryFieldDeclaration>;
  jsonldContext?: object | string;
  defaultLimit?: number;
  backend: StoreBackendSpec;
  /** Optional SPARQL queryBuildOptions overrides (flavour, primaryFields, …). */
  queryBuildOptions?: Record<string, unknown>;
};

export type CreatedStore<R extends SchemaRegistry = SchemaRegistry> =
  BaseStore<R> & Record<string, unknown>;

export type CreateStoreResult<R extends SchemaRegistry = SchemaRegistry> = {
  store: CreatedStore<R>;
  /** Logical type names from `schema.definitions`. */
  typeNames: string[];
  /** Tear down backend resources (Prisma `$disconnect`, etc.). */
  dispose?: () => Promise<void>;
};
