/**
 * Generate Prisma schema + client for the testapp item-schema, then db push.
 *
 * Run inside `nix develop .#prisma6` (engines on PATH via PRISMA_*):
 *   catalogToPrisma 6.19.1 && bun install   # once, if catalog is on 7.x
 *   bun run setup:prisma
 *   GRAVIOLA_STORE=prisma bun run seed:api
 */
import { execSync } from "child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import { jsonSchema2PrismaWithManifest } from "@graviola/json-schema-prisma-utils";
import type { JSONSchema7 } from "json-schema";

import { schema as itemSchema } from "./schema-bundle.ts";
import { toPrismaPersistenceSchema } from "./prismaSchema.ts";

const appRoot = join(import.meta.dir, "..");
const databaseUrl =
  process.env.DATABASE_URL ??
  process.env.SQLITE_URL ??
  "file:./server/prisma/dev.db";

function getPrismaMajor(): 6 | 7 {
  try {
    const out = execSync("prisma version --json", {
      encoding: "utf-8",
      env: process.env,
    });
    const major = Number.parseInt(
      (JSON.parse(out) as { prisma?: string }).prisma?.split(".")[0] ?? "6",
      10,
    );
    return major >= 7 ? 7 : 6;
  } catch {
    return 6;
  }
}

const provider = "sqlite";
const prismaMajor = getPrismaMajor();
console.log(
  `[testapp setup:prisma] Prisma major ${prismaMajor}, url=${databaseUrl}`,
);

const persistenceSchema = toPrismaPersistenceSchema(itemSchema as JSONSchema7);
const { schemaText: modelDefinitions, manifest } =
  jsonSchema2PrismaWithManifest(persistenceSchema, new WeakSet(), {
    databaseProvider: provider,
    reverseMap: {},
  });

const datasourceBlock =
  prismaMajor === 7
    ? `datasource db {
  provider = "${provider}"
}`
    : `datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}`;

const schemaContent = `// Auto-generated by apps/testapp/server/setup-prisma.ts — do not edit.
generator client {
  provider = "prisma-client-js"
  output   = "./generated/client"
}

${datasourceBlock}

${modelDefinitions}
`;

const prismaDir = join(appRoot, "server/prisma");
mkdirSync(prismaDir, { recursive: true });
writeFileSync(join(prismaDir, "schema.prisma"), schemaContent, "utf-8");
writeFileSync(
  join(prismaDir, "persistence-manifest.json"),
  JSON.stringify(manifest, null, 2),
  "utf-8",
);

const prismaConfigPath = join(appRoot, "prisma.config.ts");
if (prismaMajor === 7) {
  writeFileSync(
    prismaConfigPath,
    `import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./server/prisma/schema.prisma",
  datasource: { url: env("DATABASE_URL") },
});
`,
    "utf-8",
  );
} else if (existsSync(prismaConfigPath)) {
  rmSync(prismaConfigPath);
}

// Fresh sqlite file
const pathPart = databaseUrl.replace(/^file:/, "").replace(/^\.\//, "");
const dbPath = join(appRoot, pathPart);
if (existsSync(dbPath)) rmSync(dbPath);
for (const suff of ["-journal", "-wal", "-shm"] as const) {
  const f = dbPath + suff;
  if (existsSync(f)) rmSync(f);
}

const env = { ...process.env, DATABASE_URL: databaseUrl };
const cwd = appRoot;

execSync("prisma generate --schema=server/prisma/schema.prisma", {
  stdio: "inherit",
  env,
  cwd,
});
execSync("prisma db push --schema=server/prisma/schema.prisma", {
  stdio: "inherit",
  env,
  cwd,
});

console.log("[testapp setup:prisma] done.");
